name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      # - uses: lowlighter/metrics@main
      #   with:
      #     token: ${{ secrets.METRICS_TOKEN }}
      #     plugin_topics: yes
      #     plugin_topics_limit: 0
      #     plugin_topics_mode: icons
      #     plugin_stars: yes
      #     plugin_stars_limit: 3
      #     config_timezone: Asia/Shanghai
      - name: left
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 58b128bb8518ff23ae725b63e1e1a399

          user: NoughtQ
          template: classic
          base: header, activity, community, repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_aliases: 'RenderScript:Rust'
          plugin_lines: yes

          config_order: base.header, base.repositories, languages, base.activity+community, isocalendar
          config_padding: 0, 8 + 11%
          config_timezone: Asia/Shanghai

      - name: right
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: 23c707b05da354519787d96160cdb4e1
          
          user: NoughtQ
          template: classic
          base: metadata
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 8
          plugin_achievements_threshold: X
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME }}
          
          config_order: achievements, wakatime, base.metadata
          config_padding: 0, 8 + 11%
          config_timezone: Asia/Shanghai
